'on':
  workflow_call:
    inputs:
      azure-aks:
        required: false
        type: string
      azure-aks-rg:
        required: false
        type: string
      helm-repo-path:
        required: false
        type: string  
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUB_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
         version: 'v3.14.0' # Specify the Helm version you want (optional)
    
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: '${{ secrets.AZURE_CLIENT_ID }}'
          tenant-id: '${{ secrets.AZURE_TENANT_ID }}'
          subscription-id: '${{ secrets.AZURE_SUB_ID }}'

      - name: Checkout External Repository with Helm Chart
        uses: actions/checkout@v4
        with:
         repository: ${{inputs.helm-repo-path}}
         ref: main   
      
      - name: AKS Credentials & Helm Deployment
        run: |
             az aks get-credentials --resource-group ${{ inputs.azure-aks-rg }} --name ${{ inputs.azure-aks }} --overwrite-existing
    
             export KUBECONFIG=~/.kube/config
             kubectl config current-context
             kubectl get nodes
    
             helm upgrade --install backstage ./helm-charts \
             --namespace backstage \
             --create-namespace \
             --values ./helm-charts/values.yaml

          
      
      - name: Azure List Pods
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: >
            az aks get-credentials --resource-group ${{ inputs.azure-aks-rg }}
            --name ${{ inputs.azure-aks }} --overwrite-existing

      
         

     
