on:
    workflow_call:
        inputs:
            azure-tenant-id:
              required: false
              type: string
            azure-sub-id:
              required: false
              type: string
            azure-client-id:
              required: false
              type: string
            azure-aks:
              required: false
              type: string
            azure-aks-rg:
              required: false
              type: string    
        secrets:
          azure_github_secret:
           required: true  
permissions:
  id-token: write
  contents: read           

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:            
    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
        creds: ${{ secrets.azure_github_secret }}

    - name : Azure List Pods
      uses: Azure/cli@v2.1.0
      with:
       inlineScript:  |
          az aks get-credentials --resource-group ${{ inputs.azure-aks-rg }} --name ${{ inputs.azure-aks }} --overwrite-existing
