on:
    workflow_call:
        inputs:
            azure-tenant-id:
              required: false
              type: string
            azure-sub-id:
              required: false
              type: string
            azure-client-id:
              required: false
              type: string
            azure-aks:
              required: false
              type: string
            azure-aks-rg:
              required: false
              type: string    
        secrets:
          azureClientId::
           required: true        
          azureSudId‎:
           required: true 
          azureTenantId:
           required: true  
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
     
    permissions:
      id-token: write
      contents: read    
    
    steps:            
    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
        client-id: ${{ secrets.azureClientId }}
        tenant-id: ${{ secrets.azureTenantId }}
        subscription-id: ${{ secrets.azureSudId }}

    - name : Azure List Pods
      uses: Azure/cli@v2.1.0
      with:
       inlineScript:  |
          az aks get-credentials --resource-group ${{ inputs.azure-aks-rg }} --name ${{ inputs.azure-aks }} --overwrite-existing
