on:
    workflow_call:
        inputs:
         azure-aks:
          required: false
          type: string
         azure-aks-rg:
          required: false
          type: string    
        secrets:
         azureClientId:
          required: false        
         azureSubId‎:
          required: false 
         azureTenantId:
          required: false  
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
     
    permissions:
      id-token: write
      contents: read    
    
    steps:            
    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
        client-id: ${{ secrets.azureClientId }}
        tenant-id: ${{ secrets.azureTenantId }}
        subscription-id: ${{ secrets.azureSubId }}

    - name : Azure List Pods
      uses: Azure/cli@v2.1.0
      with:
       inlineScript:  |
          az aks get-credentials --resource-group ${{ inputs.azure-aks-rg }} --name ${{ inputs.azure-aks }} --overwrite-existing
